[2023-03-21 03:51:26,640] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: transform_etl.load_postgres manual__2023-03-21T03:51:04.005972+00:00 [queued]>
[2023-03-21 03:51:26,664] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: transform_etl.load_postgres manual__2023-03-21T03:51:04.005972+00:00 [queued]>
[2023-03-21 03:51:26,664] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:51:26,665] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-03-21 03:51:26,665] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:51:26,695] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_postgres> on 2023-03-21 03:51:04.005972+00:00
[2023-03-21 03:51:26,700] {standard_task_runner.py:52} INFO - Started process 810 to run task
[2023-03-21 03:51:26,705] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'transform_etl', 'load_postgres', 'manual__2023-03-21T03:51:04.005972+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp9kdu10k8', '--error-file', '/tmp/tmpvgfwn7sg']
[2023-03-21 03:51:26,706] {standard_task_runner.py:77} INFO - Job 22: Subtask load_postgres
[2023-03-21 03:51:26,771] {logging_mixin.py:109} INFO - Running <TaskInstance: transform_etl.load_postgres manual__2023-03-21T03:51:04.005972+00:00 [running]> on host 8d5c7b966855
[2023-03-21 03:51:26,874] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_etl
AIRFLOW_CTX_TASK_ID=load_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T03:51:04.005972+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T03:51:04.005972+00:00
[2023-03-21 03:52:18,109] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 143, in na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 233, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/load.py", line 13, in load_mysql
    df-df_json.to_sql("checkin",engine2)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 664, in f
    new_data = dispatch_to_series(self, other, op)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 265, in dispatch_to_series
    bm = left._mgr.apply(array_op, right=right)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 407, in apply
    applied = b.apply(f, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 346, in apply
    result = func(self.values, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 190, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 150, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 112, in masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
[2023-03-21 03:52:18,140] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=transform_etl, task_id=load_postgres, execution_date=20230321T035104, start_date=20230321T035126, end_date=20230321T035218
[2023-03-21 03:52:18,157] {standard_task_runner.py:91} ERROR - Failed to execute job 22 for task load_postgres
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 143, in na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 233, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/load.py", line 13, in load_mysql
    df-df_json.to_sql("checkin",engine2)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 664, in f
    new_data = dispatch_to_series(self, other, op)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 265, in dispatch_to_series
    bm = left._mgr.apply(array_op, right=right)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 407, in apply
    applied = b.apply(f, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 346, in apply
    result = func(self.values, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 190, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 150, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 112, in masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
[2023-03-21 03:52:18,216] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-03-21 03:52:18,252] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
